### PR TITLE
Fix markdown headings 3 and 4

### PR DESCRIPTION
**Pull request by knownasilya**
h3 and h4 were completely out of place so I've made them look more similar to h1 and h2.

### CODE REVIEW

**Comment by rstacruz** [comment]
Haha, I only made this repo for a theme to use for my personal sites. It seems every docpress user uses it now. :P

Great work. Thank you for your contribution. 💚

**Comment by knownasilya** [comment]
I'd actually like to see this made into the default theme 👍

**Comment by rstacruz** [comment]
Ah, neat. This was sort of an opinionated theme, with an opinionated font styles, opinionated colors and such. The default Docpress theme uses GitHub's style as is, which I think is a sensible default; even Gitbook has that, too.

Personally I view that preference as a shortcoming of the default theme, maybe it needs a bit more sprucing up :)

**Comment by knownasilya** [comment]
Or to make adding themes easier, which the new plugin idea might help.

**Comment by rstacruz** [comment]
Not quite happy with how h4 looks here though: http://ricostacruz.com/onmount/

Before:

> image

After:

> image

H3 looks fine though. :P

**Comment by knownasilya** [comment]
Maybe have it be darker?

**Pull request merged**
